### PR TITLE
Fix Schema and models

### PR DESCRIPTION
**Pull request by eduardo-salazar**

### CODE REVIEW

**Comment by yiweihuang** [comment]
Do you finish??

**Comment by eduardo-salazar** [comment]
nop :)...give me 15 minutes hehe

**Comment by eduardo-salazar** [comment]
i finish but we need to fix travis ci

**Comment by eduardo-salazar** [comment]
i am fixing it right now

**Comment by eduardo-salazar** [comment]
Done :)

**Pull request merged**
